# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=254)),
                ('author_id', models.CharField(blank=True, max_length=254)),
                ('screenshot', models.ImageField(blank=True, upload_to='uploads/comments/')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('posted', models.DateField(blank=True, null=True)),
                ('url', models.URLField()),
                ('author', models.CharField(blank=True, max_length=254)),
                ('author_id', models.CharField(blank=True, max_length=254)),
                ('screenshot', models.ImageField(blank=True, upload_to='uploads/facebook_posts/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('body', models.TextField()),
                ('posted', models.DateField(null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='facebook_post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='refugees.FacebookPost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='refugees.Post'),
        ),
    ]
