# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refugees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='posted',
        ),
        migrations.AlterField(
            model_name='comment',
            name='facebook_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refugees.FacebookPost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refugees.Post'),
        ),
    ]
