# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugees', '0002_auto_20170120_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
