# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-25 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugees', '0006_auto_20170317_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body_stemmed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
