# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-25 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refugees', '0008_auto_20170325_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refugees.CategoryType'),
        ),
    ]
