# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-26 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugees', '0009_auto_20170325_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_scraped_comments',
            field=models.BooleanField(default=False),
        ),
    ]
